### ISSUE TITLE
Gtihub action workflow for this repo

### ISSUE THREAD

**Issue by Vikash-8090-Yadav** [build-on-aws/cloud-clubs-learner-library#16]
**Is your request related to a new technology domain? Please describe.**

Greetings for the day! I would like to add some GitHub actions to this repository to save time for maintainers. Specifically, I would like to add actions for the following scenarios:

1. First-time contributors
2. When someone opens an issue
3. When someone closes an issue
4. When someone opens a pull request
5. When someone closes a pull request
6. When a maintainer merges a pull request
7. I would also like to set up an action for auto-assigning issues.

**Comment by jlooper** [comment]
I'm not sure what this is solving cc @saifeemustafaq

**Comment by saifeemustafaq** [comment]
Agreed, this wouldn't be a primary requirement for now. Maybe we can consider this in future when such process is required.
