### ISSUE TITLE
[BUG]  ` -` misisng prefix in some modules 

### ISSUE THREAD

**Issue by Vikash-8090-Yadav** [build-on-aws/cloud-clubs-learner-library#18]
**Is your request related to a problem with the existing content on the Learner Library?**
In AI/Ml, container_Kubernetes and Web and Mobile Development don't have  ` - ` followed by source.
and the remaining one has 

forex - 

![web and mobile developmewnt](https://github.com/build-on-aws/cloud-clubs-learner-library/assets/85225156/5648d1b6-f1ac-4f7e-9cd8-1bcb565f88b0)
 
### and 

![database](https://github.com/build-on-aws/cloud-clubs-learner-library/assets/85225156/4c2eb096-09d7-454e-b50a-95694c4aeb10)
  

**Describe the solution you'd like**
The one solution for this is to make all the same whether to have  ` - `  or not .

**Comment by Vikash-8090-Yadav** [comment]
If this  seems to be legit then please assign this to me , Love to work on this issue .

**Comment by Vikash-8090-Yadav** [comment]
Ok then let me know how can I become an employee like you, so that I can also contribute, Just kidding. lol :rofl: 
On a serious note, I really appreciate the great work you all are doing. I have enjoyed reading and watching workshops from this platform, which have helped me to clear up many of my concepts on technologies like EKS and Serverless. Thank you so much for providing this amazing library of resources.

**Comment by saifeemustafaq** [comment]
Thank you Vikas for utilising the platform and providing feedback.
