### ISSUE TITLE
[BUG] - Broken link in the AI/ML Module

### ISSUE THREAD

**Issue by saifeemustafaq** [build-on-aws/cloud-clubs-learner-library#8]
**Is your request related to a problem with the existing content on the Learner Library?**
A clear and concise description of what the problem is. Ex. I accessed the course but it has outdated content [...]

-> Yes, the link xyz.com is not working anymore

**Describe the solution you'd like**
A clear and concise description of what you want to happen. Ex. Do you have an updated link for this course?
-> Here is the correct link that I have found for the same resource

**Describe alternatives you've considered**
A clear and concise description of any alternative solutions or features you've considered. Ex. I have found the following updated link which can be replaced with the link on X module

**Additional context**
Add any other context or screenshots about the request here.

**Comment by jlooper** [comment]
I believe this is a test issue and can be closed?
